# Generated by Django 4.2.7 on 2023-11-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
                ('installment', models.IntegerField()),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.institution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.person')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.flag')),
            ],
        ),
    ]
